.env.local, .gitignore, app/components/__mocks__/address-data.js, app/components/__mocks__/address-data.ts, app/components/__mocks__/hazards.js, app/components/__tests__/card-hazard.test.tsx, app/components/card-hazard.tsx, app/components/pill.tsx, app/components/report.tsx, app/page.tsx
Add a "Report" component to display hazard information according to the current design solution. The component includes hazard cards and address details with placeholder for future share functionality. Adjusted for responsive layouts and integrated mock data, with all unit tests passing.
#82 
https://github.com/user-attachments/assets/c9984f65-fb40-40bf-823d-540732f039f8
=> Add report component

compose.yaml
Fixed a typo in compose.yaml
#115
Check compose.yaml to see that `postgresql` is one word.
=> Fixed typo

backend/database/init_db.py
`docker exec -it datasci-earthquake-backend-1 python backend/database/init_db.py` stopped working properly after my last commit. This PR fixes the bug I introduced.
```
docker exec -it datasci-earthquake-backend-1 python backend/database/init_db.py
```
See that it outputs the CREATE_TABLE statements it just executed.
=> HOTFIX: DB creation script

app/components/__tests__/search-bar.test.jsx, app/components/address-autofill.tsx, app/components/search-bar.jsx
PR checks are failing now that Vercel deployments are integrated. This PR fixes the Vercel deployment by addressing the underlying build error: that `document` is not defined.
One of our components relies on a third-party lib that presumably uses `document` without checking if it's running on the client or server. Loading the third-party lib dynamically (with Next's `dynamic()` function) addresses this because the server will no longer attempt to run the suspect code.
This PR also temporarily disables a related unit test until we can modify it to work with `dynamic()`.
Closes #140
Run `npm run build` locally and/or check this PR's pipeline to see if the Vercel bot announces a successful deployment.
=> Fix build error by wrapping client-only lib with dynamic

compose.yaml, next-env.d.ts, package-lock.json, package.json
Fixed an issue where npm run next-dev was not working. The problem was caused by upgrading Next.js to version 15. Downgraded Next.js to version 13, and the development server now runs successfully.
#168 
Run `npm install,` then  `npm run next-dev`
=> Bug Fix: npm run next-dev Failing to Start

.github/workflows/env_vars.yml, backend/api/config.py, backend/database/session.py, backend/etl/soft_story_properties_data_handler.py
This PR allows us to default to writing to the local DB when running the ETL process locally. 
Addresses #182.
It requires a GitHub secret change: ENVIRONMENT should be set to `ci` or `prod`. When generating the .env file, the ENVIRONMENT variable will be set to "local". It is currently in plain text.
Security-wise, this approach should be okay because:
1. We are not exposing a token, key, or host name, just an environment variable that is meaningless without the actual tokens and host names.
2. By manually changing the variable to "ci", an unauthorized user would only be able to create a session with the dummy NEON_URL variable in the .env.example, which still wouldn't allow them to write to production.
On the other hand, it is an easy change for an authorized user who needs to write to …
=> Default to local DB when running ETL locally

backend/etl/startup.sh
Script logs during backend startup:
```
backend-1           | 2025-02-09 02:56:07,142 - TsunamiDataHandler - INFO - Initialized handler for TsunamiZone with URL: https://services2.arcgis.com/zr3KAIbsRSUyARHG/ArcGIS/rest/services/CA_Tsunami_Hazard_Area/FeatureServer/0/query, page size: 1000
backend-1           | 2025-02-09 02:56:07,142 - TsunamiDataHandler - INFO - Starting data fetch for TsunamiZone
backend-1           | 2025-02-09 02:56:07,444 - TsunamiDataHandler - INFO - TsunamiZone: Received fewer records (2) than page size (1000). Assuming final page and stopping fetch. Request time: 0.30s
backend-1           | 2025-02-09 02:56:07,445 - TsunamiDataHandler - INFO - TsunamiZone: Successfully fetched 2 total features.
```
Ensured the db gets updated with the data
```
qsdatabase=# select …
```
=> [ETL] Re-enable tsunami data handler execution in backend startup script

backend/api/routers/liquefaction_api.py, backend/api/routers/soft_story_api.py, backend/api/routers/tsunami_api.py, backend/api/schemas/liquefaction_schemas.py, backend/api/schemas/soft_story_schemas.py, backend/api/schemas/tsunami_schemas.py, backend/api/tests/test_liquefaction.py, backend/api/tests/test_soft_story.py, backend/api/tests/test_tsunami.py, next-env.d.ts
Each hazard card needs a timestamp, so return the last updated timestamp for a given set of coordinates if they're in a hazard zone.
Tested by invoking the apis on localhost:8000/docs:
`is-soft-story`:
Backend service logs:
backend-1           | 2025-02-13 04:16:09,310 - backend.api.routers.soft_story_api - INFO - Checking soft story status for coordinates: lon=-122.424968, lat=37.76293
backend-1           | 2025-02-13 04:16:09,488 - backend.api.routers.soft_story_api - INFO - Soft story check result for coordinates: lon=-122.424968, lat=37.76293 - exists: True, last_updated: 2025-02-13 04:14:54.478894+00:00
backend-1           | INFO:     172.18.0.1:58282 - "GET /api/soft-stories/is-soft-story?lon=-122.424968&lat=37.76293 HTTP/1.1" 200 OK
`is-liquefaction-zone`:
backend-1           | …
=> Add `last_updated` datetime to the `is-*` apis.

app/components-test-lib/page.tsx, app/components/__tests__/card-hazard.test.tsx, app/components/address-mapper.tsx, app/components/card-hazard.tsx, app/components/home-header.tsx, app/components/pill.tsx, app/components/report.tsx, app/components/search-bar.jsx, app/data/data.js
This PR updates hazard cards to use real API data instead of mock data. Changes include:
- Displaying status pills based on API responses as provided by latest design: Low Rist / At Risk
- Updating hazard type names and descriptions to Soft Story, Tsunami, and Liquefaction per the latest design.
- Ensuring components handle API data in the format:
`values = [
{ exists: false, last_updated: null },
{ exists: false, last_updated: null },
{ exists: false, last_updated: null },
];`
corresponding to `[isSoftStory, isInTsunamiZone, isInLiquefactionZone]`.
#230 
=> Update cards backend data

app/components/search-bar.jsx
replaces mock data with API-returned data for hazard cards
When an address is selected, see that its updated hazard data aligns with the actual dataset.
> I did detect an anomaly during my testing: "100 10th St, San Francisco" appears to show tsunami as "high risk", which doesn't seem right at first blush. If it's incorrect, not sure if related to code correctness or something else.
=> replace mock hazard data with data returned from API

app/home-skeleton.tsx, app/loading.tsx
Loading skeleton loaded by `loading.tsx` so that static UI appears while waiting for API calls to return. Perceived loading time is reduced due to early UI rendering.
Closes #284
1. Wipe the browser cache
2. Load app locally (or preview app). Observe sections of page load immediately, and then the map loads later.
3. Load app in production (https://safehome.report) or from current main branch. Observe how several seconds pass before any of the page is rendered, in contrast to this branch's deployment.
=> Use loading skeleton as fallback UI for main page to reduce perceived load time

app/api/fetch-data.ts
Turn on server-side caching for the initial API calls. Revalidate cache every 24 hours. This will improve initial load time of the map layer data (soft stories, seismic and tsunami polygons) after the first visit (by any visitor, doesn't need to be current user).
The end result will mean the map itself loads more quickly AND the layer data on top of it since the map rendering is currently blocked until data is received. Receiving the data more quickly enables the speedup.
Closes #279
1. Clear browser cache
2. Visit app locally or preview app in browser
3. Observe slow initial load time of map, including layer data, of several seconds (optionally, check Next logs and observe Next Cache logs show cache MISSES and timings in the several thousands of milliseconds).
2. Reload app in browser
3. …
=> Opt into server-side caching with a revalidation period of 24 hours

app/components/search-bar.jsx, app/data/data.js
this implements a temporary fix that memoizes the first calls made to mapbox using the useCallback React function. we should consider a refactor later down the line, as this is not intended to be a permanent solution.
tested locally using local frontend development build and backend docker containers.
before:
https://github.com/user-attachments/assets/fdfcb466-2e3c-4117-a5c0-6b5e0abcf3ec
after:
https://github.com/user-attachments/assets/6d2cee60-c6e4-4cbe-b86d-78416e6b3514
=> cache results from search bar

app/components/map.tsx
Added cooperative gestures to the map to prevent scrolling from being blocked by zoom. Now, zooming requires holding an additional key.
#229 
Open the web application and try scrolling the map. The map appears dimmed, and a message prompts you to press and hold an additional key to scroll.
=> cooperativeGestures added

app/components-test-lib/page.tsx, app/components/address-mapper.tsx, app/components/card-hazard.tsx, app/components/home-header.tsx, app/components/pill.tsx, app/components/report.tsx, app/components/search-bar.jsx
Improved hazard data fetching resilience and UI feedback with the following changes:
- Failure to make one API call does not block the rest.
- While hazard data is loading, a spinner is shown instead of the status pill.
- If no data is received, a “No data” pill appears.
- On error, a friendly Toast message is displayed using Chakra UI component.
#274 
- Use Network Throttling in Browser DevTools to see the loading spinner.
- Stop the backend container to simulate a No data response.
=> Handle address search errors

app/components/map.tsx, app/components/search-bar.jsx
Mapbox autocomplete options updated to prioritize San Francisco addresses in search results. Additionally, the update resolved the issue with the delayed autocomplete trigger — now suggestions appear as soon as you type three characters.
#299 
#298
Start typing an address in the search box—results should now show up quicker and highlight San Francisco addresses first.
=> Limit Autocomplete and Improve Trigger Threshold

README.md, app/about/page.tsx, app/components-test-lib/page.tsx, app/components/address-mapper.tsx, app/components/card-container.tsx, app/components/card-info.tsx, app/components/footer.tsx, app/components/header.tsx, app/components/home-header.tsx, app/components/map.tsx, app/components/report-hazards.tsx, styles/theme.ts
> NOTE: Please merge bottom card replacement PR #344 first.
This PR addresses feedback on whitespace. It also uses Chakra theme defaults where custom ones appear unnecessary.
Lastly, it adjusts the blue heading colors.
Compare latest deployment (scroll to bottom and look for the last "View Deployment" link) to prod site at different breakpoints. Also compare to [Figma desktop versions](https://www.figma.com/design/PV3mZIbiGI1mxHHGOPeOqx/SafeHome-Design--20250325-Copy-?node-id=2082-809) (mobile versions are forthcoming).
=> standardize whitespace across the app with focus on horizontal padding

app/components/address-mapper.tsx
hide illustration on main page to allow for text to be more readable on mobile
#359 
Before
After
Open web site on mobile and note that the illustration no longer appears.
Alternatively, open in desktop browser and shrink width until hitting mobile responsive breakpoint. Note that the illustration no longer appears.
=> Fix hide illustration on mobile

compose.yaml
The healthchecks will now be much further apart (500s) after Docker has verified that they are healthy.
#341 
Start the container and time the healthchecks.  The first ones are 10 seconds apart, but the ones after are 500s apart.
=> Increased healthcheck intervals

app/components/card-hazard.tsx
Fixes the CardHazard component so that it closes the "More Info" panel when clicking the CardHazard for a second time. It seems to be necessary for the PopoverTrigger component to render a button in order to get the expected default behavior
Closes https://github.com/sfbrigade/datasci-earthquake/issues/401
run the app and check that the desired behavior is shown
=> Close Hazard card when clicking a second time
