- app/layout.tsx
- app/page.tsx
- app/providers.tsx
- package-lock.json
- package.json
- styles/theme.ts
Installed ChakraUI and added a provider and a custom theme. Changed background to make sure that theme works.
[Integrate ChakraUI for UI Components #36](https://github.com/sfbrigade/datasci-earthquake/issues/36)
> Integrate chakraUI

- app/components-test-lib/page.tsx
- app/components/mock-button.tsx
Created an initial page for the components test library and added a mock button as a reference example.
#39
> Component test page

- app/components/mock-button.test.tsx
- jest.config.ts
- package-lock.json
- package.json
Jest is installed and configured to ensure compatibility with the current setup. A sample test for the MockButton component has been created and runs successfully using the relevant test script, confirming Jest is functional and ready for new test cases.
#52
> Jest installed, configured, and running successfully

- app/components/footer.tsx
- app/components/header.tsx
- app/layout.tsx
- app/page.tsx
- styles/theme.ts
Implemented a responsive base layout in accordance with design specifications for spacing, alignment, and breakpoints. It includes header, footer, and main content area sections, tested to confirm layout responsiveness across various screen sizes. Basic placeholders for future component integration have also been added.
#56
> Base application layout

- app/components/footer.tsx
- app/components/header.tsx
- app/layout.tsx
- app/page.tsx
- package-lock.json
- package.json
- styles/theme.ts
Added design tokens for colors, typography, and breakpoints into the Chakra UI theming system. These tokens are based on the design system and ensure consistency across all pages and components. 
#37
> Add design tokens

- app/components-test-lib/page.tsx
- app/components/__mocks__/address-data.js
- app/components/__mocks__/hazards.js
- app/components/__tests__/card-hazard.test.tsx
- app/components/card-hazard.tsx
- app/components/pill.tsx
- styles/theme.ts
Implemented a reusable Hazards Card component that displays key hazard information and adapts responsively based on design specifications. It is available in the [Component Test Library](http://localhost:3000/components-test-lib). The component currently accepts variable data directly, with support for passing data via props to be added during integration with the Report component. Unit tests have been created and passed.
#70
> Hazards card component created

- backend/api/models/combined_risk.py
- backend/database/init.sql
@trew-boisvert @katiefg @agennadi and I have contributed to an init.sql that contains testable data.
Contributes to but does not close #93, for which more data is needed.
Follow the steps in the README to compose the containers and test the database.
> Updated init.sql

- backend/api/models/addresses.py
- backend/api/models/tsunami.py
- backend/database/init_db.py
- backend/etl/address_data_handler.py
- backend/etl/data_handler.py
- backend/etl/tsunami_data_handler.py
Populated tsunami table.
#73
Run `docker-compose up`
Run `docker exec -it my_postgis_db psql -U postgres -d qsdatabase` to interact with the db container.
Run `select count(*) from tsunami_zones;` -> the table shouldn't be empty.
> Populated tsumami table

- README.md
- backend/api/models/landslide_zones.py
- backend/api/models/seismic_hazard_zones.py
- backend/database/init_db.py
- backend/etl/landslide_data_handler.py
- backend/etl/seismic_data_handler.py
- backend/etl/tsunami_data_handler.py
Populated landslide and seismic tables.
Updated README: added a troubleshooting section for Docker.  
#73 
Run `docker-compose up`.
Run `docker exec -it my_postgis_db psql -U postgres -d qsdatabase` to interact with the db container.
Run `select count(*) from landslide_zones;` -> the table shouldn't be empty.
Run `select count(*) from seismic_hazard_zones;` -> the table shouldn't be empty.
> Populate landslide

- app/about/page.tsx
- app/components/__tests__/header.test.tsx
- app/components/__tests__/heading.test.tsx
- app/components/header.tsx
- app/components/heading.tsx
- app/data/data.js
- app/page.tsx
- styles/theme.ts
Created a dedicated About page with the structure in accordance to [the current design solution](https://www.figma.com/design/AGadwQcQH5kNn2D93TVOAC/Design?node-id=1534-2053&p=f&t=uDosjWYNx3aWL4Aj-0) and placeholder content. This version displays sample text, while the final information, including project details and external links, will be added once decisions on the wording are finalized. 
The layout is fully responsive, mobile-friendly, and accessibility standards have been considered. Unit tests are passing successfully.
#127
> Add about page

- .github/workflows/ci.yml
- backend/api/models/liquefaction_zones.py
- backend/api/schemas/liquefaction_schemas.py
- backend/database/init.sql
- backend/etl/soft_story_properties_data_handler.py
Changed the type of the `identifier` field.
Added an absolute import to fix the GitHub Actions `etl_to_neon` workflow.
> Fixed liquefaction table

- README.md
- app/components/map.tsx
- package.json
- pull_request_template.md
This PR adjusts the map styling and mock data that's displayed (confined to `map.tsx`). This is **_the main change._** Details below:
- show ONLY non-compliant soft stories as per @mjjsf due to user feedback
- change to monochrome map
- adjust dot and layer colors/opacity
- move tsunami layer below seismic layer
- prevent labels from being obscured
- disable 2D and 3D map rotation
This PR also addresses two chores, described below.
First, it updates `README` and the pull request template with instructions on "clean" pull requests (also see copy/pasted example below under "Clean commits"):
<p align="center" width="100%">
</p>
Lastly, this PR also contains dev scripts commits (in `package.json`) pulled from #155 (currently blocked) that:
- add `npm install` to `next-dev` and adds a script …
> Adjust map styling, add dev scripts, update PR template and README

- package.json
Adds a `clean` script--currently just for front end--to attempt ensuring a "from scratch" project folder for reproducible dev server experience. Also adds a rebuild script to help ensure same for a build in dev environment.
Run `npm run rebuild`
> add clean and rebuild script

- backend/api/main.py
Resolved cors error by adding a middleware to fastapi backend allowing requests from localhost and port 3000
_add a short description_
_reference to relevant issue_
- [ x] Bugfix
- [x ] I think tests are unnecessary
Go to api docs and run an endpoint to check if we get 500 error
_testing description here: i.e. run app, go to x page, see that it does y_
> #175 Update cors middleware

- README.md
Mention how to run pytest with local Docker in README
_testing description here: i.e. run app, go to x page, see that it does y_
> dock-docker-pytest

- app/components/address-mapper.tsx
- app/components/map.tsx
- app/page.tsx
Updated the map component to display real data from the backend instead of mock data. 
#165 
> Replaced Mock Data with Real Backend Data for the Map

- .pytest.ini
- backend/Dockerfile
- backend/etl/data_handler.py
- backend/etl/request_handler.py
- backend/etl/retry.py
- backend/etl/session_manager.py
- backend/etl/tests/test_data_handler.py
- pytest.ini
Refactor the `data_handler` logic to make testing easier.
Also moved out logic for `session creation`, `retries` and `http requests` into new files.
[_reference to relevant issue_](https://github.com/sfbrigade/datasci-earthquake/issues/202)
Startup the stack as `docker-compose up` and ensure all the data handlers in the startup script are successfully executed.
> Refactor `data_handler` to improve testability

- app/components-test-lib/page.tsx
- app/components/address-mapper.tsx
- app/components/report.tsx
- app/components/search-bar.jsx
- next-env.d.ts
This PR updates the displayed address and shows the "Share Report" option when a user selects an address from the search suggestions. 
Hazard data will be updated once the API calls are ready.
#166 
> Show address and share report upon user search

- .github/workflows/ci.yml
- Dockerfile
- api/index.py
- backend/Dockerfile
- backend/api/routers/health_api.py
- backend/api/tags.py
- compose.yaml
- Add healthcheck for frontend and backend containers
- CI needs to wait for all containers healthy before testing
#238 
As long as passing CI
> 174 - add health check for docker containers

- README.md
- requirements.txt
I added pytest-cov to document the extent of test coverage to the repository and included a one-liner shell command to display it on the terminal to the main README.
#203 
Take down the containers and delete them and their images and volumes
Rebuild and compose the containers
Then do either 
1)
Enter the datasci-earthquake-backend-1 container with docker exec -it datasci-earthquake-backend-1 bin/bash
Navigate to the backend folder with cd backend
Run pytest with coverage with pytest --cov=backend
or
2) 
Run docker exec -w /backend datasci-earthquake-backend-1 pytest --cov=backend
> Added pytest code coverage and a one-liner shell command to obtain it

- app/components/search-bar.jsx
Fixed an error from the previous merge.
> Fixed an error

- app/page.tsx
- vercel.json
Initial page load is slow. This is an attempt to partially address it by making all API calls concurrently. Additionally, it increases Vercel Function timeout from the default of 10s to 20s to prevent timeouts that appear to occur on initial (but not subsequent) loads.
Attempts to address #248.
> ~Depends on #241 being merged in first. Please don't approve until it is, thank you!~
> #241 is merged in now, so feel free to finish reviewing and approving.
Load page without cache, see if it loads any more quickly
> attempt to parallelize server API calls

- backend/database/session.py
_add a short description_
_reference to relevant issue_
_testing description here: i.e. run app, go to x page, see that it does y_
> feat: configure sqlalchemy pool

- app/components/address-mapper.tsx
- app/components/map.tsx
- app/components/search-bar.jsx
- app/home-skeleton.tsx
- app/page.tsx
1. Added ChakraUI toast for initial loading error.
2. Updated error handling for hazard search per address.
#272 
To test initial error handling:
1.  Change URL for CDN in .env file 
3. Stop database in Docker
4. Try reloading the web app.
> Handle initial load errors

- backend/api/routers/liquefaction_api.py
- backend/api/routers/soft_story_api.py
- backend/api/routers/tsunami_api.py
Updated the Soft Story query to use `ST_DWithin` for spatial proximity checks instead of exact equality comparison.
Replaced the `ST_Contains` check with `ST_Intersects` for tsunami zones.
Replaced the `ST_Contains` check with `ST_Intersects` for liquefaction zones.
#351
Run the app in docker and type in several addresses - make sure that the hazards are returned correctly. 
> Optimized spatial calculations

- app/about/page.tsx
- app/components/header.tsx
- app/components/heading.tsx
- app/components/home-header.tsx
- app/data/data.js
The web app's styles and layout have been updated to appear presentable and functional on mobile devices.
Additionally, wording for Structural Safety and its detailed information has been changed.
#350 
Use your browser’s DevTools to simulate a mobile device and verify that the web app displays correctly and remains functional.
> Mobile friendly

- app/about/page.tsx
- app/data/data.js
Update team members and roles on About page to latest info
Check against SafeHome Canvas in Slack.
> update team members and roles

- app/data/data.js
team member got back to me w/last name so adding it
#357 
Note added last name
> add missing last name for team member

- .env.example
- .github/workflows/ci.yml
CI triggered by the `push` action used `.env.example` instead of `.env`
#368 
Merge into develop 
> use .env for pushes

- .env.example
- .github/workflows/ci.yml
- .github/workflows/etl_to_neon.yml
- backend/database/update-postgis.sh
#311
#368
Create a fork and open a PR
> Enabled PRs from forks

- app/home-skeleton.tsx
- app/page.tsx
Changes to  external links
#490
Click external links
> Open new links in new tab
